"""
monitoring/reporting/report.py

Generates human-readable (summary.txt) and machine-readable
(reports/monitoring_report.json) monitoring reports.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from monitoring.config import MONITORING_ROOT, REPORTS_DIR
from monitoring.models import MonitoringSnapshot

logger = logging.getLogger(__name__)


_STATUS_EMOJI = {
    "HEALTHY": "✅",
    "WARNING": "⚠️",
    "CRITICAL": "❌",
    "UNKNOWN": "❓",
    "NOT_CONFIGURED": "⚙️",
}


def _status_icon(status: str) -> str:
    return _STATUS_EMOJI.get(status, "?")


def generate_summary(
    snapshot: MonitoringSnapshot,
    monitoring_root: Path | None = None,
) -> str:
    """
    Write data/monitoring/summary.txt and return the text content.
    """
    root = monitoring_root or MONITORING_ROOT
    root.mkdir(parents=True, exist_ok=True)
    summary_file = root / "summary.txt"

    lines: list[str] = []
    lines.append("=" * 60)
    lines.append("  E-COMMERCE PLATFORM MONITORING REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(
        f"Overall Status : {_status_icon(snapshot.overall_status.value)} "
        f"{snapshot.overall_status.value}"
    )
    lines.append(f"Run ID         : {snapshot.run_id}")
    lines.append(f"Timestamp      : {snapshot.timestamp}")
    lines.append("")
    lines.append("-" * 60)
    lines.append("  COMPONENT STATUS")
    lines.append("-" * 60)

    for name, result in snapshot.components.items():
        icon = _status_icon(result.status.value)
        lines.append(f"  {icon} {name:<22} {result.status.value}")

    lines.append("")
    lines.append("-" * 60)
    lines.append(f"  ALERTS  ({len(snapshot.alerts)} total)")
    lines.append("-" * 60)

    if snapshot.alerts:
        for alert in snapshot.alerts:
            lines.append(
                f"  [{alert.severity}] {alert.component}.{alert.metric}: "
                f"{alert.message}"
            )
    else:
        lines.append("  No alerts generated.")

    lines.append("")
    lines.append("-" * 60)
    lines.append("  COMPONENT DETAILS")
    lines.append("-" * 60)

    for name, result in snapshot.components.items():
        lines.append(f"\n  [{name.upper()}]")
        if result.warnings:
            for w in result.warnings:
                lines.append(f"    ⚠️  {w}")
        if result.errors:
            for e in result.errors:
                lines.append(f"    ❌ {e}")
        if not result.warnings and not result.errors:
            lines.append("    No warnings or errors.")

    lines.append("")
    lines.append("=" * 60)
    lines.append("  Generated by Functionality 20: Monitoring")
    lines.append("=" * 60)

    text = "\n".join(lines)

    try:
        summary_file.write_text(text, encoding="utf-8")
        logger.info("Summary written to %s", summary_file)
    except Exception as exc:
        logger.error("Failed to write summary.txt: %s", exc)

    return text


def generate_json_report(
    snapshot: MonitoringSnapshot,
    monitoring_root: Path | None = None,
) -> dict:
    """
    Write data/monitoring/reports/monitoring_report.json and return the dict.
    """
    root = monitoring_root or MONITORING_ROOT
    reports_dir = root / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    report_file = reports_dir / "monitoring_report.json"
    snap_dict = snapshot.to_dict()

    # Enrich with generation metadata
    snap_dict["generated_at"] = datetime.now(timezone.utc).isoformat()
    snap_dict["platform"] = "Real-Time E-Commerce Data Engineering & AI Analytics"
    snap_dict["functionality"] = 20

    try:
        report_file.write_text(
            json.dumps(snap_dict, indent=2, default=str),
            encoding="utf-8",
        )
        logger.info("JSON report written to %s", report_file)
    except Exception as exc:
        logger.error("Failed to write monitoring_report.json: %s", exc)

    return snap_dict
